language: ruby

before_install:
  - gem update bundler

rvm:
  - 2.0.0
  - 2.1.0
  - 2.3.1

gemfile:
  - gemfiles/rails-3.2.gemfile
  - gemfiles/rails-4.0.gemfile
  - gemfiles/rails-4.1.gemfile
  - gemfiles/rails-4.2.gemfile
  - gemfiles/rails-5.0.gemfile
  
